server:
  port: 8888
keycloak:
  realm: sso-realm
  auth-server-url: http://localhost:8081/auth
  resource: sso-app
  bearer-only: true
  enable-basic-auth: false

credentials:
  keycloak:
    client: realm-management
    secret: ae46122a-4398-45ce-8530-ff11a74e66af

spring:
  application:
    name: sso
